### ISSUE TITLE
auto reloading for partials

### ISSUE THREAD

**Issue by carols10cents** [rustbridge/website#38]
What happened:

- I ran `npm start` and the site loaded in the browser
- I changed some of the content in data/content/workshops.md
- I expected the site to reload by itself and show my changes, they did not show up
- I checked in the terminal for errors and I saw "Change detected data/content/workshops.md" and I didn't see any errors
- I looked at package.json and saw that changes to the markdown should be reflected in the templates/partials, but I didn't see my changes in templates/partials/workshops.mustache
- If I stop the server and restart it, I *do* see my changes reflected in the template and on the site

📚 🌻

**Comment by ashleygwilliams** [comment]
this is a feature request for auto reloading of content that is in partials. this is a 2 parter, but can probably use the same implementation.

basically when live-server is watching, on change it should re run `npm run build`
