### ISSUE TITLE
Potential site design

### ISSUE THREAD

**Issue by alilleybrinker** [rustbridge/website#53]
I spent a bit of time tonight tinkering with some design ideas for the Rust Bridge site. It doesn't use the new logo, but that could easily be changed. Any thoughts? Is this something we'd want to use?

!["Site design"](https://photos-5.dropbox.com/t/2/AAAmVI9cwEYX67n4ySD2Hw13Hs12LSRkLN1Z8CLLNDwzUQ/12/10519016/png/32x32/3/1503482400/0/2/Screen%20Shot%202017-08-22%20at%2022.05.10.png/EK_h7AcYgr4CIAIoAigE/0oWervzMYeG-iWNIsTKU4JlGNba5NoRFsTAd72QdjXs?dl=0&size=2048x1536&size_mode=3)

**Comment by alilleybrinker** [comment]
The red is the red used for Rust Conf 2017, and the green is the green from the current site.

The font is Omnes by Darden Studio. Font choice is of course flexible if the preference is to stick entirely to free fonts.

**Comment by alilleybrinker** [comment]
Okay, for some reason the image appears broken now. Here is a link: https://www.dropbox.com/s/65qw8hkp9ucls64/Screen%20Shot%202017-08-22%20at%2022.05.10.png?dl=0

**Comment by ashleygwilliams** [comment]
hey! so this site *is* a redesign and is not actually even live yet. i'm not sure we're ready to completely reconsider everything as it is in progress now, but if you have suggestions on incrementally improving whats already in progress that would be great. thanks!
