### ISSUE TITLE
building a Rust website material

### ISSUE THREAD

**Issue by jonknapp** [rustbridge/website#67]
Please forgive me if I missed it, but is https://github.com/rustbridge/rust-emergency-compliment the "build a website" portion of a RustBridge event? Are there any docs or teaching notes/strategies around it?

**Comment by komaeda** [comment]
@jonknapp Yep, but we're currently looking at replacing it with something more suited towards the 2019 Rust ecosystem.

**Comment by jonknapp** [comment]
Awesome, thanks. Looking forward to hosting a local event in a few months. We'll post about it once we get a date/venue locked down.
