### ISSUE TITLE
Is rustbridge.com down?

### ISSUE THREAD

**Issue by JohnTitor** [rustbridge/website#74]
Some folks have found that we cannot access rustbridge.com (cannot connect to the server at rustbridge.com) at Discord.

@fmoko Could you take a look?

**Comment by manyinsects** [comment]
Yup, on it

**Comment by manyinsects** [comment]
Domain expired, I renewed it so in a couple of hours it should be all good again

**Comment by JohnTitor** [comment]
Thanks for fixing it!
